Implement drafts and a CheckAuth middleware
nit-app/nit-backend pull request #8
Opened 2024-05-03 13:25 UTC by GlafiraSmiirnova

2024-05-04 13:56 UTC, emmitrin requested changes
🥑

2024-05-04 13:56 UTC, emmitrin commented on services/events/create_draft.go
> +			return nil, err
Нужно делать все записи в одной транзацкии (вместе с самим созданием хедера) и ревертить если тег не добавился

2024-05-04 13:56 UTC, emmitrin commented on services/events/create_draft.go
> +	return draftHeader, nil
возможно, стоит вынести это в отдельную приватную функцию

2024-05-04 13:56 UTC, emmitrin commented on models/event.go
> +	Tags               []string         `json:"tags" binding:"required"`
недостаточная валидация, пропустит массив тэгов типа `["", "", " "]`

2024-05-04 13:56 UTC, emmitrin commented on services/events/create_draft.go
> +	newUuid := uuid.New()
тут комм был просто для примера, это можно не выносить в отдельную переменную)

2024-05-08 22:11 UTC, GlafiraSmiirnova commented on services/events/create_draft.go
> +	newUuid := uuid.New()
это штоб потом в `QueryRowContext(c, draftQuery, uuid)` закинуть

2024-05-09 11:54 UTC, emmitrin approved these changes

2024-05-09 11:54 UTC, merged